### PR TITLE
Added support for RabbitMQ queue arguments

### PR DESCRIPTION
**Pull request by ByteFlinger**
Added support for RabbitMQ Queue Arguments (See https://www.rabbitmq.com/queues.html#optional-arguments for details)

### CODE REVIEW

**Comment by asim** [comment]
What is your reason for adding all these changes? Are you using this at a company somewhere?

**Comment by ByteFlinger** [comment]
> What is your reason for adding all these changes? Are you using this at a company somewhere?

Yes, we are using it in a project. We wrote our own RabbitMQ abstraction to support automatic reconnection however given the way that the amqp library works, it is rather complicated code that we'd rather avoid having to write ourselves as it has already been done by Go Micro which has a nice community.

This specific change allows us to set things like queue size to avoid unbounded queues

**Comment by asim** [comment]
Ok, thanks, appreciated. Having merged your other changes I believe this creates a conflict.

**Comment by ByteFlinger** [comment]
I'll fix it

**Comment by ByteFlinger** [comment]
Thank you for the merges

**Pull request merged**
