### PR TITLE
receive message with single go routine

### PR DESCRIPTION
**Pull request by quexer**
- In the case of "fast produce/ slow consumer ",   user often hope to store messages in RabbitMQ.
- but current implementation will lead to plenty of goroutines,  read all message into memory. If the process crash at that time,  we'll lose many messages.
- with the new implementation,  we leave the choice to the user.  one can always start new goroutines in EventHandler if he wants.

```golang
micro.RegisterSubscriber("foo.bar", srv, func(ctx context.Context, msg *Foo)error{
      go dealMessage(msg)
})
```
or keep serial process

```golang
micro.RegisterSubscriber("foo.bar", srv, func(ctx context.Context, msg *Foo)error{
      dealMessage(msg)
})
```

 this provides more flexibility

### CODE REVIEW

**Comment by vtolstov** [comment]
I think that we need to use single process always and user in handler can spawn goroutine.(I'm prefer to use goroutine pool like ants)

**Comment by vtolstov** [comment]
@asim ehat you think about this?

**Comment by asim** [comment]
I guess it depends. Message processing was synonymous with handling requests. The go net/http server fires a go routine for every new connection. So as per that pattern we'd do the same for messages. But I understand that services might not have the ability to process at the rate required.

**Comment by vtolstov** [comment]
golang net/http have ability to use Listener so you can easy throttle requests and provide own mechanism like goroutine pool or some other stuff. In our case we don't have this, so i'm prefer simplicity in this case. So each user can use own decision how to handle messages.

**Comment by quexer** [comment]
> golang net/http have ability to use Listener so you can easy throttle requests and provide own mechanism like goroutine pool or some other stuff. In our case we don't have this, so i'm prefer simplicity in this case. So each user can use own decision how to handle messages.

Agree.  

We should not assume the consumer can always handle messages in time.   otherwise  the concept "Message Queue" makes no sense

thanks

**Pull request merged**
