### PR TITLE
Make a function to change default exchange name

### PR DESCRIPTION
**Pull request by HuyTikii**
Recommend for #402

### CODE REVIEW

**Comment by asim** [comment]
Why cant you use the existing Exchange option?

**Comment by HuyTikii** [comment]
> Why cant you use the existing Exchange option?

As I presented in issue ticket, I need to use the default rabbitmq exchange. I mean I need exchange name is a empty string. But If I define exchange name is a empty string, go-plugin will reassign the default rabbitmq exchange is "micro":

```
DefaultExchange = exchange{
		name: "micro",
	}
```

```
if len(ex.name) == 0 {
		ex = DefaultExchange
	}
```

**Comment by asim** [comment]
In response to what you were asking for https://github.com/micro/go-plugins/commit/6c9897967b5894b233e71fc4e694a64a0d5ab304

DefaultExchange is now a global Exchange type which you can change. We also no longer check for the blank exchange name, so we're just taking whatever is provided.

**Comment by HuyTikii** [comment]
It sounds great...thank you very much :)

**Pull request closed without merging**
