### PR TITLE
Implement msgpackrpc codec

### PR DESCRIPTION
**Pull request by bruth**
Signed-off-by: Byron Ruth <b@devel.io>

### CODE REVIEW

**Comment by bruth** [comment]
Thanks for merging. Any feedback?

**Comment by asim** [comment]
A lot more code than I was expecting for a codec lol. Appreciate the contribution. Maybe some styling nitpicks like extra spaces where there shouldn't really be but otherwise lgtm.

**Comment by bruth** [comment]
Much of the code is for packing the message based on the spec since it requires an array, but also taking care to do it efficiently:

```
BenchmarkRequestEncode-4     	20000000	        80.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkRequestDecode-4     	10000000	       187 ns/op	       4 B/op	       1 allocs/op
BenchmarkResponseEncode-4    	20000000	        79.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkResponseDecode-4    	10000000	       219 ns/op	       5 B/op	       1 allocs/op
BenchmarkNotificationEncode-4	20000000	        70.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkNotificationDecode-4	10000000	       168 ns/op	       4 B/op	       1 allocs/op
```

**Comment by bruth** [comment]
Obviously the benchmark does not include a realistic payload, but since the request and response structs expect a `msgp.Encodable` and `msgp.Decodable`, those would likely be generated from the `msgp` tool and thus near zero-alloc.

**Pull request merged**
