### PR TITLE
Fix handling of RabbitMQ URLs that use amqps

### PR DESCRIPTION
**Pull request by st3v**
* do not exclude amqps from prefix check
* use TLS dialer for amqps URLs

### CODE REVIEW

**Comment by asim** [comment]
LGTM

**Comment by st3v** [comment]
Thanks Asim. 

On a somewhat related note. What's your take on logging inside these plugin packages? Currently RabbitMQ connection errors are simply swallowed since `broker.Connect` always returns `nil`. I'm not the biggest fan of that approach but can live with it for now. What makes it problematic though is that `tryToConnect` doesn't log the error in any way. So if something goes wrong, I have no idea what is going on. Took me longer than it should have to find this bug today. Logging would have helped. What would you think of adding a pluggable logger to the broker options?

**Comment by st3v** [comment]
@asim ^^^

**Comment by asim** [comment]
The logging issue is one that comes up every now and then. I've avoided it for a while as I wasn't really sure the right approach to fixing it. It's something that needs to be thought about basically across all the packages.

On this issue. I guess there's two ways it could be addressed. Either to have an option to add a logger as you said or rework the way the connection logic works. The logger is probably going to be the simpler choice for now.

**Comment by st3v** [comment]
Thanks. I might take a stab at the logger option when I get a chance. I assume you'd prefer a structured logger.

**Comment by asim** [comment]
So structured logging has been addressed in the go-platform here https://godoc.org/github.com/micro/go-platform/log. I've avoided any sort of logging interface in go-micro because I don't think its relevant to the core. Having an option in the broker or anywhere else would just be supplying a simple interface to it or it would default to say the go log package.

The simple interface to be passed in as an option would be something like:
```
type Logger interface {
    Errorf(format string, args ...interface{})
    Fatalf(format string, args ...interface{})
}
```

**Comment by st3v** [comment]
Cool. That looks pretty much like what I had in mind.

**Pull request merged**
