### PR TITLE
Use `Drain()` to unsuscribe or close connection

### LINKED ISSUE #328: nats broker graceful disconnect/unsubscribe support
The nats official [document](https://nats.io/documentation/writing_applications/subscribing/) suggests to use `Drain()` for both connection to disconnect and subscriber to unsubscribe, so that any cached outgoing msg could be flushed and any pending msg will be processed by handler before returns (or drain timeout).

So please consider to use `Drain()` to implement both `Broker.Disconnect()` and `Subscriber.Unsubscribe()` so that nats broker could have a graceful shutdown.

### PR DESCRIPTION
**Pull request by magodo**
Resolves #328

### CODE REVIEW

**Comment by vtolstov** [comment]
I'm suggest to  not change default,but add option to broker, so if someone pass wait option when create micro service, he also can pass this option to broker.

**Comment by magodo** [comment]
Updated

**Comment by asim** [comment]
There's some sort of existing nats test failing. Can some check why?

**Comment by magodo** [comment]
I am also figuring why, since it passes in my local environment.




获取 Outlook for Android







On Wed, May 15, 2019 at 7:09 PM +0800, "Asim Aslam" <notifications@github.com> wrote:












There's some sort of existing nats test failing. Can some check why?

**Comment by magodo** [comment]
> There's some sort of existing nats test failing. Can some check why?

This seems to be some environment issue. The error complains address `nats://127.0.0.1:4222` hasn't been set, while the corresponding address is `nats://localhost:4222`.

It is because of this [commit](https://github.com/nats-io/nats.go/commit/8df1cb3fa94387f013a2561ce8b2f1530f24b8c1#diff-0344230acb7b1a1d6a77d726a9a43695). Since this is not in the latest release of go-nats(cur v1.7.2), so I don't have this issue until go-plugins's go.mod updated to use the master branch of go-nats.

But I wonder why the CI env is using the master branch of go-nats instead of the one specified in go.mod...

Do you think it make sense to modify the testcase now or later?

**Comment by asim** [comment]
We'll sort it out later. @vtolstov what do you think of the PR?

**Comment by vtolstov** [comment]
I think that we need also train timeout settings... i'm push my suggestions, and also i want to add someting like this to stan too.

**Comment by magodo** [comment]
There is no timeout mechanism provided by nats itself, if we must have timeout, then it would be some problematic solution with potential go routine leak issue.

**Comment by vtolstov** [comment]
https://godoc.org/github.com/nats-io/nats.go#DrainTimeout

**Comment by vtolstov** [comment]
i mean this timeout. Without it i don't understand , how much time this drain can take

**Comment by magodo** [comment]
OK, but isn't this already able to set via `func Options(opts nats.Options) broker.Option`?

**Comment by vtolstov** [comment]
yes, nevermind. DefaultDrainTimeout already present and so not needs to be set explicit..
@asim as i see error happened in ci not only on this pr, can you merge this pr ? As i see it works (in my testing)

**Comment by asim** [comment]
Can you fix the test as part of this? It's related to nats.

**Comment by vtolstov** [comment]
yes, i'm try

**Comment by vtolstov** [comment]
@asim i don't know why tests are failing.
```
go test -v
=== RUN   TestInitAddrs
=== RUN   TestInitAddrs/brokerOpts:_set_broker_addresses_through_a_broker.Option_in_constructor
=== RUN   TestInitAddrs/brokerInit:_set_broker_addresses_through_a_broker.Option_in_broker.Init()
=== RUN   TestInitAddrs/natsOpts:_set_broker_addresses_through_the_nats.Option_in_constructor
=== RUN   TestInitAddrs/default:_check_if_default_Address_is_set_correctly
--- PASS: TestInitAddrs (0.00s)
    --- PASS: TestInitAddrs/brokerOpts:_set_broker_addresses_through_a_broker.Option_in_constructor (0.00s)
    --- PASS: TestInitAddrs/brokerInit:_set_broker_addresses_through_a_broker.Option_in_broker.Init() (0.00s)
    --- PASS: TestInitAddrs/natsOpts:_set_broker_addresses_through_the_nats.Option_in_constructor (0.00s)
    --- PASS: TestInitAddrs/default:_check_if_default_Address_is_set_correctly (0.00s)
PASS
ok      github.com/micro/go-plugins/broker/nats 0.008s
```

**Comment by magodo** [comment]
> > There's some sort of existing nats test failing. Can some check why?
> 
> This seems to be some environment issue. The error complains address `nats://127.0.0.1:4222` hasn't been set, while the corresponding address is `nats://localhost:4222`.
> 
> It is because of this [commit](https://github.com/nats-io/nats.go/commit/8df1cb3fa94387f013a2561ce8b2f1530f24b8c1#diff-0344230acb7b1a1d6a77d726a9a43695). Since this is not in the latest release of go-nats(cur v1.7.2), so I don't have this issue until go-plugins's go.mod updated to use the master branch of go-nats.
> 
> But I wonder why the CI env is using the master branch of go-nats instead of the one specified in go.mod...
> 
> Do you think it make sense to modify the testcase now or later?

I think I have already clarified about it.. Or no?

**Comment by asim** [comment]
We'll fix it separately.

**Comment by vtolstov** [comment]
Yes,ci is strange.it not use go mod by default on tests, travis file needs to be fixed

**Pull request merged**
