### PR TITLE
refactor(logger): logger fields changed to map[string]interface{}

### PR DESCRIPTION
**Pull request by xmlking**

### CODE REVIEW

**Comment by asim** [comment]
You're introducing some sort of platform specific settings into the logger. This likely isn't the right way to configure it. We never want direct references to a cloud provider or environment in something like this. The logger has log levels and other settings. they should be configured externally

**Comment by vtolstov** [comment]
i'm agree with @asim

**Comment by xmlking** [comment]
Will move out gcp and update

**Comment by asim** [comment]
Thank you!

**Comment by xmlking** [comment]
Work In Progress W.I.P
I am replacing with my `go-micro` version for testing.  this has to be removed after `go-micro` merge

```
replace github.com/micro/go-micro/v2 => github.com/xmlking/go-micro/v2  master
```

**Pull request merged**
