### PR TITLE
WIP: resolve dependencies error 

### PR DESCRIPTION
**Pull request by leaxoy**
This solve #363

1. remove `example` dependency by replace `server/grpc/grpc_test.go` pb import
2. run `go mod tidy`
3. use specific version of `k8s` rather than replace.

### CODE REVIEW

**Comment by leaxoy** [comment]
CI for 1.11 success, but 1.12 failed on `TestBreaker`
=== RUN   TestBreaker
--- FAIL: TestBreaker (0.01s)
    hystrix_test.go:43: Expecting tripped breaker, got {"id":"go.micro.client","code":500,"detail":"error selecting test.service node: not found","status":"Internal Server Error"}
FAIL
FAIL	github.com/micro/go-plugins/wrapper/breaker/hystrix	0.029s

can some one look into this

**Comment by asim** [comment]
As stated previously. We're not deleting the grpc client and server because we've only just archived go-grpc which still references it. This PR will not be merged. Please indicate why you've not read the comment in the previous PR you created.

**Comment by leaxoy** [comment]
This not delete grpc package just alias it to the `go-micro` one, and not break backward compatibility

**Comment by vtolstov** [comment]
i'm merge this and fix after

**Pull request merged**
