### PR TITLE
Fix service name validation for k8s labels

### PR DESCRIPTION
**Pull request by asim**

### CODE REVIEW

**Comment by rileyr** [comment]
The same regex is run on the annotations. We've added the `serviceName()` call to lines:

https://github.com/micro/go-plugins/blob/master/registry/kubernetes/kubernetes.go#L73
https://github.com/micro/go-plugins/blob/master/registry/kubernetes/kubernetes.go#L102

We are unsure if this should also be added to https://github.com/micro/go-plugins/blob/master/registry/kubernetes/kubernetes.go#L138.

**Comment by asim** [comment]
Is there a restriction on annotation keys? I don't see this anywhere in the documentation.

**Comment by twking7** [comment]
Looking through old kubernetes PRs, I see they mention annotation keys as having the same regex as labels: https://github.com/kubernetes/kubernetes/issues/4628

**Comment by asim** [comment]
Multiple operations have to change here. Annotation keys were used in the ListServices call to get the list of services. The annotations themselves must be unmarshalled to get the actual name since its impossible to reverse the encoded key.

Please try now.

**Comment by rileyr** [comment]
👍  Looks good!

**Comment by asim** [comment]
Thanks for the help.

**Pull request merged**
