### PR TITLE
wrapper: opentracing use GlobalTracer in case of nil Tracer

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
i'm check it and it works for me.

**Comment by asim** [comment]
Why not just assign to ot rather than creating a new value?

**Comment by vtolstov** [comment]
if i pass to wrapper some value that have nil and assign to it inside wrapper func, i think that original value modified, or i'm wrong?

**Comment by asim** [comment]
I'm not exactly sure what you're saying but passing ot should be a one time occurrence and when you receive something as an argument to a function thats not a pointer you get a copy.

**Comment by vtolstov** [comment]
yes, i'm understand.
i fix opentracing.go and also fix formating, because my git says 'warning: CRLF will be replaced by LF'

**Comment by asim** [comment]
This is now basically an untrackable PR. Are you using go fmt?

**Comment by vtolstov** [comment]
Yes,code formated with gofmt.
This is because prev version uses rl+lf, but git uses on linux lf.

**Pull request merged**
