### PR TITLE
kafka: allow multi topic subscriptions

### LINKED ISSUE #145: kafka: cannot subscribe to several topics
Hi,

There is an error when I try to register to several kafka topics.
The code is
```golang
service := micro.NewService(
	micro.Name(ServiceName),
	micro.Broker(kafka.NewBroker(func(o *broker.Options) { o.Addrs = brokerURLs })),
)
service.Init()

handler := &MyHandler{}
notification.RegisterNotificationHandler(service.Server(), handler)

if err := micro.RegisterSubscriber(aTopic, service.Server(), handler.aEvent); err != nil {
	log.Fatalf("Cannot register subscriber %s : %s", aTopic, err)
}
if err := micro.RegisterSubscriber(bTopic, service.Server(), handler.bEvent); err != nil {
	log.Fatalf("Cannot register subscriber %s : %s", bTopic, err)
}
```

The second call to `RegisterSubscriber` produces this error: `cluster: client is already used by another consumer`.
Is there a way to subscribe to several kafka topics?

### PR DESCRIPTION
**Pull request by alexppxela**
Avoid crash on disconnection
Resolves #145 

---
This change is [Reviewable](https://reviewable.io/reviews/micro/go-plugins/147)

### CODE REVIEW

**Comment by asim** [comment]
One thing I'm wondering. Does this change not introduce a bug where if multiple Subscribe calls are made to the same topic they'll use the same client? Which will essentially throw the same error as before.  

Also the map should be protected by a mutex considering it can be concurrently accessed

**Comment by alexppxela** [comment]
Ok, I did not know if several clients can subscribe on the same topic. In this case, it is better to use a slice,, I'll change and protect the list.

**Comment by asim** [comment]
Ping. Any update on this?

**Comment by alexppxela** [comment]
I've commited https://github.com/micro/go-plugins/pull/147/commits/2005ea9f0acfb2a9aaceedad4f8e50e3d3f067cd last week to allow multi subscription on the same topic and add mutex.
For kafka, it sounds good to me.
Travis is broken on kubernetes tests. I do not know what could be happen.

**Comment by asim** [comment]
Looks like a transient issue. All good. Merging now.

**Pull request merged**
