### PR TITLE
Allow for OAuth2 client credentials flow

### PR DESCRIPTION
**Pull request by st3v**
Now that the fargo PR has been merged... 

Let me know what you think.

### CODE REVIEW

**Comment by asim** [comment]
I'm sold. You tried it out?

**Comment by st3v** [comment]
yeah, that's what you saw running online. :)

**Comment by asim** [comment]
Ah awesome. Well in that case. Merging. Thanks for the awesome addition Stev! Brings us one step closer to Micro on PCF as a real solution.

**Comment by st3v** [comment]
You're welcome. Would love to see that happen!

I wrote some glue code to make micro easier to use on CF. It's still quite rough but maybe I could clean it up and move it into some sort of plugin or something. It basically get's all the app and service details from the environment and sets up the default registry and server accordingly.

**Comment by asim** [comment]
Interesting. Sounds like a potential wrapper implementation for new service. I've always imagined micro providing core tools that could then be layered for a specific purpose. The most common example is a company creating their own service library that initialises all the defaults, extra flags, etc.

So maybe we could have a pcf repo or something dedicated to that and anything else involved.

```
import "github.com/micro/pcf/go/micro"

service := micro.NewService()
```

**Comment by st3v** [comment]
Yeah that would make sense and it's not too far off the hack I've got right now ... https://github.com/st3v/pcf-micro

Anyway, need to catch some sleep. :sleeping:

**Pull request merged**
