### PR TITLE
feature: upgrade consul registry plugin to adapt micro v2

### PR DESCRIPTION
**Pull request by x1nchen**

### CODE REVIEW

**Comment by asim** [comment]
We're going to do an update for v2 across everything

**Comment by x1nchen** [comment]
emmm... I found the tests in module registry/consul passed in travis log https://travis-ci.org/micro/go-plugins/builds/643900032#L2396

I have ran the tests locally either and it's ok.

**Comment by x1nchen** [comment]
> We're going to do an update for v2 across everything

OK.Thanx.

**Comment by vtolstov** [comment]
fixed in v2.0.0 release

**Pull request closed without merging**
