### PR TITLE
make nats transport respect configured listen address & use named queue

### PR DESCRIPTION
**Pull request by antness**
Useful for selector/named plugin.
Tried to make it maximum backward compatible with old behaviour.

### CODE REVIEW

**Comment by asim** [comment]
Not really happy with this implementation. It implies when there's no address specified or its ":0" then it should do subscribe sync otherwise queue subscribe. That's really ugly. It's probably more appropriate for there to be a ListenOption which allows queue subscription.

**Comment by antness** [comment]
Yes, it's ugly. I prefer to call it "implementation detail".
Actually it could use queue subscription in both cases. But I'm not sure what is performance hit of queues on the nats's side.
For me, it looks like too low level and plugin-specific option for micro's ListenOption.

**Comment by asim** [comment]
It probably makes more sense to make the default behaviour a queue subscription (but first researching the implications of that) and parsing the address to determine whether a unique inbox should be assigned or whether the address should be taken verbatim.

**Comment by asim** [comment]
So spending a little time looking at this I was able to come up with a solution in 3 lines BUT on further inspection I believe this will likely breaking bidirectional streaming behaviour. When creating a "stream" using a message bus, it establishes something of a pseudo socket but all existing communication with the remote end is still expected to come in through the main topic. With a QueueSubscribe this behaviour will basically break and messages will be lost, a "socket" won't actually be established. The only way to fix that is to potentially create a new topic for a socket but this is not behaviour I want to change right now. So I'm going to close this PR for the time being.

**Pull request closed without merging**
