### PR TITLE
Refactored nats transport and added tests and benchmarks

### PR DESCRIPTION
**Pull request by phifty**

### CODE REVIEW

**Comment by asim** [comment]
This is really not the ideal way to refactor. It's difficult to track what's changing and what's actually adding value. The registry changes should not appear in the same PR and there has been no discussion around how to actually solve the initial problem stated in the previous issue. The method used here is very ad-hoc. Sending a message with a "close" header is not ideal.

Please close and open a new issue so it can be discussed as this will be related to other connectionless setups like rabbitmq, etc.

**Comment by phifty** [comment]
Hey, it's just a proposal. It's - for sure - far away from ideal, since I just quick fixed it :-) We needed a fast solution, because the processes were crashing. I would call it a starting point.

The refactoring is basically just a code split into multiple files (one per type).

**Comment by asim** [comment]
PRs are not really proposals but I get that you need a fix. A quick fix is not the ideal thing to merge. A refactor (splitting files) can be done separately to fixing the issue.

**Comment by phifty** [comment]
I guess everyone has a different workflow ;-)

**Pull request closed without merging**
