### PR TITLE
add AWS snssqs broker plugin

### PR DESCRIPTION
**Pull request by alex-broad**

### CODE REVIEW

**Comment by alex-broad** [comment]
So the build that's failing looks like it's the older go version. At any rate it's failing in tests that seem unrelated to this broker plugin. Can anyone assist please?

**Comment by asim** [comment]
Is this being used anywhere?

**Comment by alex-broad** [comment]
We're using it in HPE. SNS offers additional subscription options above SQS so this module is useful to allow publishing to SNS topics and subscriptions to SQS queues...

**Comment by asim** [comment]
Interesting. Anything you can share about the deployment scale of micro at HPE?

**Comment by alex-broad** [comment]
We're evaluating it right now.

**Comment by asim** [comment]
Feel free to join the slack and let us know of any issues you run into

**Pull request merged**
