### PR TITLE
cleanup mod, remove grpc transport, server, client 

### PR DESCRIPTION
**Pull request by leaxoy**
1. cleanup mod file to remove replace section
2. remove grpc transport, server, client in favor of those included in `go-micro`

### CODE REVIEW

**Comment by vtolstov** [comment]
please rebase to master and push, so we can see ci status of this pr

**Comment by leaxoy** [comment]
Ok, this PR failed, due to k8s client-go error.
``` go
# k8s.io/client-go/rest
../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```
do you known how to fix it

**Comment by asim** [comment]
You should look at the current go.mod. It fixes this issue by pinning the version of k8s.io/apimachinery

**Comment by leaxoy** [comment]
Thanks, I will try pin it to fix this

**Comment by asim** [comment]
Can you please start a new PR, this is conflicting. You should start with master and go from there.

**Pull request closed without merging**
