### PR TITLE
Fix log with fields and log with error

### LINKED ISSUE #499: [BUG] logger/logrus: Fields() method doesn't work
```go
func (l *logrusLogger) Fields(fields map[string]interface{}) logger.Logger {
	// shall we need pool here?
	// but logrus already has pool for its entry.
	return &logrusLogger{logrus.WithFields(fields).Logger, l.opts}
}
```
**Fields()** method doesn't work. 

```go
func TestWithFields(t *testing.T) {
	logger.DefaultLogger = NewLogger(logger.WithOutput(os.Stdout)).Fields(map[string]interface{}{
		"k1": "v1",
		"k2": 123456,
	})

	logger.Log(logger.InfoLevel, "testing: Info")
	logger.Logf(logger.InfoLevel, "testing: %s", "Infof")
}
```

It prints:

```sh
INFO[0000] testing: Info
INFO[0000] testing: Infof
```

However, we expect like this:

```sh
INFO[0000] testing: Info                                 k1=v1 k2=123456
INFO[0000] testing: Infof                                k1=v1 k2=123456
```

### PR DESCRIPTION
**Pull request by skyjia**
- Fix #499 
- Added `func WithLogger(l logrus.StdLogger) logger.Option`. Allow to initialize `Logger` with an existing `*logrus.Logger` or `*logrus.Entry`.

### CODE REVIEW

**Comment by vtolstov** [comment]
Why you create another interface?

**Comment by skyjia** [comment]
**logrus.FieldLogger** interface doesn't contain **Log** and **Logf** methods and both **logrus.Logger** and **logrus.Entry** implement them.

https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc#FieldLogger

```go
func (l *logrusLogger) Log(level logger.Level, args ...interface{}) {
	l.Logger.Log(loggerToLogrusLevel(level), args...)
}

func (l *logrusLogger) Logf(level logger.Level, format string, args ...interface{}) {
	l.Logger.Logf(loggerToLogrusLevel(level), format, args...)
}
```
 **Log** and **Logf** are used to print leveled log here.

**Comment by skyjia** [comment]
Due to [**logrus.FieldLogger**](https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc#FieldLogger) interface doesn't define `Tracef(format string, args ...interface{})` and `Trace(args ...interface{})` methods, we have to use Log or Logf methods instead of `switch` statement on `logger.Level`.

Even though [**logrus.Ext1FieldLogger**](https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc#Ext1FieldLogger) interface is an extension for **logrus.FieldLogger**, it doesn't recommend to use this. 

@vtolstov

**Comment by skyjia** [comment]
I refactor it with **logrus.StdLogger** interface. Please review it again. @vtolstov

**Pull request merged**
