### PR TITLE
fix(#487): set CallerSkipFrameCount

### PR DESCRIPTION
**Pull request by egyel**
based on: https://github.com/rs/zerolog/issues/91

### CODE REVIEW

**Comment by vtolstov** [comment]
You try to use logger instance directly or via helper?

**Comment by egyel** [comment]
> You try to use logger instance directly or via helper?

I used the logger instance directly. (I also corrected it in my bug report)

**Comment by vtolstov** [comment]
I think, that if you try to set logger.DefaultLogger , and use logger.Info
for example, stack trace will be again not right.

пт, 28 февр. 2020 г., 11:03 egyel <notifications@github.com>:

**Comment by egyel** [comment]
I just pushed my testing repo: https://github.com/egyel/logtest
I ran: `go run *.go` then for testing the logs in the handler: `micro call go.micro.srv.logtest Logtest.Call '{"name":"John"}'`
The logs finecorrect for me.

I think, an additional option to be able to set the CallerSkipFrameCount would be nice to have. (I've tried to add a ReportCallerWithCount option, but my knowledge of go/micro is not enough yet)

**Comment by vtolstov** [comment]
I think about it. May be we can have some autodetection.

**Comment by xmlking** [comment]
@egyel  I am resetting all `zerolog`   package global values at the beginning of `Init()` and then set what user pass in the options.  So resetting the default should be `zerolog.CallerSkipFrameCount = 2`

you can add a new option function (e.g., `CallerSkipFrameCount(count int)`)  in [zerolog/options.go](https://github.com/micro/go-plugins/blob/master/logger/zerolog/options.go) if you want to add this feature.

**Comment by xmlking** [comment]
by the way, I think you can set all `zerolog` global values  yourself in your code: 
For example, add this in the binging of your `main.go`
```
import "github.com/rs/zerolog"
zerolog.CallerSkipFrameCount = 4
```

**Comment by vtolstov** [comment]
can we detect how much we need to skip ?

**Comment by egyel** [comment]
> @egyel I am resetting all `zerolog` package global values at the beginning of `Init()` and then set what user pass in the options. So resetting the default should be `zerolog.CallerSkipFrameCount = 2`
> 
> you can add a new option function (e.g., `CallerSkipFrameCount(count int)`) in [zerolog/options.go](https://github.com/micro/go-plugins/blob/master/logger/zerolog/options.go) if you want to add this feature.

@xmlking thanks

**Comment by vtolstov** [comment]
why by default skip count is 4 ?

**Comment by egyel** [comment]
I simply iterated over the numbers to find the one that shows the correct line.
I am not sure if you were asking me. If you were, sorry for this delay.

**Comment by vtolstov** [comment]
we prefer to have such thing as Option to logger. Like @xmlking suggests

**Pull request merged**
