### PR TITLE
broker/nats.Connect: double-check, avoid conn leaks

### PR DESCRIPTION
**Pull request by MaruHyl**

### CODE REVIEW

**Comment by vtolstov** [comment]
can you explain more about adding this code?

**Comment by vtolstov** [comment]
Before connect we already check for nil conn and Is.Connected(), why not move check to near Connect with full mutex lock, disconnect if already connected, and after that connect and unlock mutex?

**Comment by MaruHyl** [comment]
@vtolstov  how about this?
```
        n.RLock()
	if n.conn != nil && n.conn.IsConnected() {
		n.RUnlock()
		return nil
	}
	n.RUnlock()

        n.Lock()
        defer n.Unlock()
        if n.conn != nil && n.conn.IsConnected() {
		return nil
	}
	// ....
	c, err := opts.Connect()
	if err != nil {
		return err
	}
	n.conn = c
	return nil
```

**Comment by vtolstov** [comment]
I don't think that this is right. See options, you may have reconnect handler, so when you first check you may be not connected, because something happened and client disconnected. But after check reconnect may happen, so n.conn does not nil and n.conn.IsConnected()  is true.
I think that we need to discuss behavior first in case of all options present for nats and decide how to deal ...

**Comment by MaruHyl** [comment]
@vtolstov I think Connect should make a new Conn in CLOSED, DISCONNECTED, DRAINING, otherwise it won't.
```go
        n.Lock()
	defer n.Unlock()

	status := nats.CLOSED
	if n.conn != nil {
		status = n.conn.Status()
	}

	switch status {
	case nats.CONNECTED, nats.RECONNECTING, nats.CONNECTING:
		return nil
	default: // DISCONNECTED or CLOSED or DRAINING
		opts := n.nopts
		opts.Servers = n.addrs
		opts.Secure = n.opts.Secure
		opts.TLSConfig = n.opts.TLSConfig

		// secure might not be set
		if n.opts.TLSConfig != nil {
			opts.Secure = true
		}

		c, err := opts.Connect()
		if err != nil {
			return err
		}
		n.conn = c
		return nil
	}
```

**Comment by MaruHyl** [comment]
@vtolstov 
It cant be DISCONNECTED in reconnecting.
See https://github.com/nats-io/go-nats/blob/master/nats.go#L1894.
Status graph:
```
... status which we could make a new Conn
CONNECTED->DISCONNECTED->CLOSED
CONNECTED->DRANING->CLOSED
... status which we do not need to make a new one
RECONNECTING->CONNECTED
CONNECTING->CONNECTED
```

**Comment by vtolstov** [comment]
yes, makes sense.

**Comment by vtolstov** [comment]
did you mind provide fixed pr?

**Comment by MaruHyl** [comment]
@vtolstov done.

**Comment by vtolstov** [comment]
In case of DRAINING may be we need to wait before connect and change n.conn ? What do you think?

**Comment by MaruHyl** [comment]
@vtolstov 
You are right.But it is a bit difficult to implement this logic.
Two ways to do this:
1.register a CloseHandler 
2.check status in a loop
There is no other simpler way.

`But in fact conn will not into DRAINING state, because micro.Broker does not export conn.Drain()`
So I think this is enough, that the conn changed here will eventually close instead of leaking.

**Comment by vtolstov** [comment]
ok i think this is enough. @asim can you merge?

**Pull request merged**
